[2024-12-20T18:49:05.628+0000] {processor.py:157} INFO - Started process (PID=56) to work on /opt/airflow/dags/data_generation_dag.py
[2024-12-20T18:49:05.629+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/data_generation_dag.py for tasks to queue
[2024-12-20T18:49:05.631+0000] {logging_mixin.py:154} INFO - [2024-12-20T18:49:05.630+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/data_generation_dag.py
[2024-12-20T18:49:05.641+0000] {logging_mixin.py:154} INFO - [2024-12-20T18:49:05.636+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/data_generation_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_generation_dag.py", line 5, in <module>
    from src.data.gerador_dados import (gerar_produtos, gerar_clientes,
ModuleNotFoundError: No module named 'src'
[2024-12-20T18:49:05.642+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/data_generation_dag.py
[2024-12-20T18:49:05.690+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/data_generation_dag.py took 0.068 seconds
[2024-12-20T18:49:35.853+0000] {processor.py:157} INFO - Started process (PID=60) to work on /opt/airflow/dags/data_generation_dag.py
[2024-12-20T18:49:35.855+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/data_generation_dag.py for tasks to queue
[2024-12-20T18:49:35.857+0000] {logging_mixin.py:154} INFO - [2024-12-20T18:49:35.856+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/data_generation_dag.py
[2024-12-20T18:49:35.866+0000] {logging_mixin.py:154} INFO - [2024-12-20T18:49:35.864+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/data_generation_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_generation_dag.py", line 5, in <module>
    from src.data.gerador_dados import (gerar_produtos, gerar_clientes,
ModuleNotFoundError: No module named 'src'
[2024-12-20T18:49:35.866+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/data_generation_dag.py
[2024-12-20T18:49:35.921+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/data_generation_dag.py took 0.077 seconds
[2024-12-20T19:03:51.340+0000] {processor.py:157} INFO - Started process (PID=26) to work on /opt/airflow/dags/data_generation_dag.py
[2024-12-20T19:03:51.342+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/data_generation_dag.py for tasks to queue
[2024-12-20T19:03:51.344+0000] {logging_mixin.py:154} INFO - [2024-12-20T19:03:51.343+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/data_generation_dag.py
[2024-12-20T19:03:51.352+0000] {logging_mixin.py:154} INFO - [2024-12-20T19:03:51.349+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/data_generation_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_generation_dag.py", line 5, in <module>
    from src.data.gerador_dados import (gerar_produtos, gerar_clientes,
ModuleNotFoundError: No module named 'src'
[2024-12-20T19:03:51.352+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/data_generation_dag.py
[2024-12-20T19:03:51.407+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/data_generation_dag.py took 0.076 seconds
